/**
 * Created on 2024/10/22
 */
package pendingitems.model

public class StyleConfig {
    public static let IMAGE_MARGIN = 4
    public static let ICON_GUTTER = 4
    public static let OPERATION_BUTTON_PADDING = 4
    public static let MENU_IMAGE_SIZE = 24
    public static let MENU_HEIGHT = 56
    public static let TEXT_MARGIN_LEFT = 40
    public static let IMAGE_MARGIN_RIGHT = 30
    public static let LIST_ITEM_GUTTER = 12
    public static let BORDER_WIDTH = 3
    public static let TODO_ITEM_HEIGHT = 80
    public static let TODO_ITEM_PADDING_VERTICAL = 4
    public static let IMAGE_ICON_OK_SIZE = 15
    public static let ANIMATION_DURATION = 600
    public static let CUSTOM_CHECKBOX_SIZE = 20
    public static let IMAGE_SIZE = 32
    public static let FONT_SIZE_MAX = 18
    public static let FONT_SIZE_MIN = 14
}

